In [1]:
from pathlib import Path
from typing import Union, Optional
import pandas as pd
import numpy as np
import logging

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

In [2]:
# Use pathlib for robust path handling
BASE_DIR = Path.cwd().parent 
PROCESSED_DATA_DIR = BASE_DIR / "data_processed"
CONFIG_DIR = BASE_DIR / "config"
BRFSS_ZIP_FILE = PROCESSED_DATA_DIR / "BRFSS_2015_2024.zip"

# Ensure directories exist
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

In [3]:
def read_zipped_csv(
    zip_path: Union[str, Path],
    **read_csv_kwargs
) -> pd.DataFrame:
    """
    Read a single-CSV .zip file into a pandas DataFrame.

    Parameters
    ----------
    zip_path : str or Path
        Path to the .zip file (containing exactly one CSV, or a CSV
        with the same name as the zip).
    **read_csv_kwargs :
        Any extra keyword args passed through to pandas.read_csv
        (e.g. sep, dtype, parse_dates).

    Returns
    -------
    pd.DataFrame
    """
    zip_path = Path(zip_path)
    # For a single CSV in the zip, this is enough:
    return pd.read_csv(zip_path, compression="zip", **read_csv_kwargs)

In [4]:
# Load the BRFSS data
df = read_zipped_csv(BRFSS_ZIP_FILE)
logging.info(f"Initial data loaded with {df.shape[0]} rows. and columns: {df.shape[1]}")

2026-01-18 22:24:37 - INFO - Initial data loaded with 4410255 rows. and columns: 21

In [5]:
# Convert YEAR to categorical
df['YEAR'] = df['YEAR'].astype('category')
logging.info("Converted 'YEAR' column to categorical type.")

2026-01-18 22:24:37 - INFO - Converted 'YEAR' column to categorical type.

In [6]:
def print_unique_values(data, columnName):
    unique_column_values = data[columnName].unique()
    if pd.api.types.is_numeric_dtype(unique_column_values):
        unique_column_values = np.sort(unique_column_values)
    column_datatype = data[columnName].dtype
    num_unique_column_values = len(unique_column_values)
    print(f'{num_unique_column_values} Unique values in column {columnName} of type {column_datatype}: {unique_column_values}')

# For each column, print unique values
for col in df.columns:
    print_unique_values(df, col)

10 Unique values in column YEAR of type category: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Categories (10, int64): [2015, 2016, 2017, 2018, ..., 2021, 2022, 2023, 2024]
3 Unique values in column HEALTH_STATUS of type float64: [1. 2. 9.]
5 Unique values in column PHYSICAL_HEALTH_STATUS of type float64: [ 1.  2.  3.  9. nan]
4 Unique values in column MENTAL_HEALTH_STATUS of type int64: [1 2 3 9]
3 Unique values in column EXERCISE of type float64: [1. 2. 9.]
3 Unique values in column HEALTH_CARE_COVERAGE of type float64: [1. 2. 9.]
5 Unique values in column SMOKER of type float64: [1. 2. 3. 4. 9.]
4 Unique values in column DRINKER of type float64: [1. 2. 7. 9.]
3 Unique values in column SOCIAL_DRINKER of type float64: [1. 2. 9.]
3 Unique values in column HEAVY_ALCOHOL_CONSUMPTION of type float64: [1. 2. 9.]
3 Unique values in column HEART_ATTACK of type float64: [ 1.  2. nan]
5 Unique values in column STROKE of type float64: [ 1.  2.  7.  9. nan]
7 Unique values in column DIABETES of type float64: [ 1.  2.  3.  4.  7.  9. nan]
3 Unique values in column ARTHRITIS of type float64: [ 1.  2. nan]
8 Unique values in column MARITAL_STATUS of type float64: [ 1.  2.  3.  4.  5.  6.  9. nan]
10 Unique values in column EMPLOYMENT of type float64: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
4 Unique values in column SEX of type float64: [1. 2. 7. 9.]
14 Unique values in column AGE_CATEGORIES of type float64: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
5 Unique values in column BMICAT of type float64: [ 1.  2.  3.  4. nan]
5 Unique values in column EDUCATION_LEVEL of type float64: [1. 2. 3. 4. 9.]
8 Unique values in column INCOME of type float64: [1. 2. 3. 4. 5. 6. 7. 9.]

In [7]:
# Display the dataset info
logging.info("Data information:\n")
df.info()

2026-01-18 22:24:44 - INFO - Data information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410255 entries, 0 to 4410254
Data columns (total 21 columns):
 #   Column                     Dtype
---  ------                     -----
 0   YEAR                       category
 1   HEALTH_STATUS              float64
 2   PHYSICAL_HEALTH_STATUS     float64
 3   MENTAL_HEALTH_STATUS       int64
 4   EXERCISE                   float64
 5   HEALTH_CARE_COVERAGE       float64
 6   SMOKER                     float64
 7   DRINKER                    float64
 8   SOCIAL_DRINKER             float64
 9   HEAVY_ALCOHOL_CONSUMPTION  float64
 10  HEART_ATTACK               float64
 11  STROKE                     float64
 12  DIABETES                   float64
 13  ARTHRITIS                  float64
 14  MARITAL_STATUS             float64
 15  EMPLOYMENT                 float64
 16  SEX                        float64
 17  AGE_CATEGORIES             float64
 18  BMICAT                     float64
 19  EDUCATION_LEVEL            float64
 20  INCOME                     float64
dtypes: category(1), float64(19), int64(1)
memory usage: 677.2 MB

In [8]:
logging.info("Data description:")
df.head()

2026-01-18 22:24:53 - INFO - Data description:

,YEAR,HEALTH_STATUS,PHYSICAL_HEALTH_STATUS,MENTAL_HEALTH_STATUS,EXERCISE,HEALTH_CARE_COVERAGE,SMOKER,DRINKER,SOCIAL_DRINKER,HEAVY_ALCOHOL_CONSUMPTION,...,STROKE,DIABETES,ARTHRITIS,MARITAL_STATUS,EMPLOYMENT,SEX,AGE_CATEGORIES,BMICAT,EDUCATION_LEVEL,INCOME
0,2015,2.0,3.0,3,2.0,1.0,3.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,4.0,2.0,2.0
1,2015,1.0,1.0,1,1.0,2.0,1.0,2.0,1.0,1.0,...,2.0,3.0,2.0,2.0,3.0,2.0,7.0,3.0,4.0,1.0
2,2015,2.0,3.0,1,9.0,9.0,9.0,9.0,9.0,9.0,...,1.0,3.0,1.0,2.0,7.0,2.0,11.0,2.0,2.0,9.0
3,2015,2.0,3.0,3,2.0,1.0,4.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,3.0,2.0,5.0
4,2015,2.0,3.0,1,2.0,1.0,4.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,2.0,3.0,9.0

In [9]:
# Display the first few rows
logging.info("First few rows of the dataset:")
df.head()

2026-01-18 22:24:56 - INFO - First few rows of the dataset:

,YEAR,HEALTH_STATUS,PHYSICAL_HEALTH_STATUS,MENTAL_HEALTH_STATUS,EXERCISE,HEALTH_CARE_COVERAGE,SMOKER,DRINKER,SOCIAL_DRINKER,HEAVY_ALCOHOL_CONSUMPTION,...,STROKE,DIABETES,ARTHRITIS,MARITAL_STATUS,EMPLOYMENT,SEX,AGE_CATEGORIES,BMICAT,EDUCATION_LEVEL,INCOME
0,2015,2.0,3.0,3,2.0,1.0,3.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,4.0,2.0,2.0
1,2015,1.0,1.0,1,1.0,2.0,1.0,2.0,1.0,1.0,...,2.0,3.0,2.0,2.0,3.0,2.0,7.0,3.0,4.0,1.0
2,2015,2.0,3.0,1,9.0,9.0,9.0,9.0,9.0,9.0,...,1.0,3.0,1.0,2.0,7.0,2.0,11.0,2.0,2.0,9.0
3,2015,2.0,3.0,3,2.0,1.0,4.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,3.0,2.0,5.0
4,2015,2.0,3.0,1,2.0,1.0,4.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,2.0,3.0,9.0

In [10]:
# For each column, replace 'Not Sure' or 'Refused' codes with NaN

replace_unsure_refused = {
    'HEALTH_STATUS': {9: np.nan},
    'PHYSICAL_HEALTH_STATUS': {9: np.nan},
    'MENTAL_HEALTH_STATUS': {9: np.nan},
    'EXERCISE': {9: np.nan},
    'HEALTH_CARE_COVERAGE': {9: np.nan},
    'SMOKER': {9: np.nan},
    'DRINKER': {7: np.nan, 9: np.nan},
    'SOCIAL_DRINKER': {9: np.nan},
    'HEAVY_ALCOHOL_CONSUMPTION': {9: np.nan},
    #'HEART_ATTACK': {},
    'STROKE': {7: np.nan, 9: np.nan},
    'DIABETES': {7: np.nan, 9: np.nan},
    #'ARTHRITIS': {},
    'MARITAL_STATUS': {9: np.nan},
    'EMPLOYMENT': {9: np.nan},
    'SEX': {7: np.nan, 9: np.nan},
    'AGE_CATEGORIES': {14: np.nan},
    #'BMICAT': {},
    'EDUCATION_LEVEL': {9: np.nan},
    'INCOME': {9: np.nan}
}

df.replace(replace_unsure_refused, inplace=True)

In [11]:
# Display the dataset info
logging.info("Data information:\n")
df.info()

2026-01-18 22:25:06 - INFO - Data information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410255 entries, 0 to 4410254
Data columns (total 21 columns):
 #   Column                     Dtype
---  ------                     -----
 0   YEAR                       category
 1   HEALTH_STATUS              float64
 2   PHYSICAL_HEALTH_STATUS     float64
 3   MENTAL_HEALTH_STATUS       float64
 4   EXERCISE                   float64
 5   HEALTH_CARE_COVERAGE       float64
 6   SMOKER                     float64
 7   DRINKER                    float64
 8   SOCIAL_DRINKER             float64
 9   HEAVY_ALCOHOL_CONSUMPTION  float64
 10  HEART_ATTACK               float64
 11  STROKE                     float64
 12  DIABETES                   float64
 13  ARTHRITIS                  float64
 14  MARITAL_STATUS             float64
 15  EMPLOYMENT                 float64
 16  SEX                        float64
 17  AGE_CATEGORIES             float64
 18  BMICAT                     float64
 19  EDUCATION_LEVEL            float64
 20  INCOME                     float64
dtypes: category(1), float64(20)
memory usage: 677.2 MB

In [12]:
logging.info("Data description:")
df.head()

2026-01-18 22:25:10 - INFO - Data description:

,YEAR,HEALTH_STATUS,PHYSICAL_HEALTH_STATUS,MENTAL_HEALTH_STATUS,EXERCISE,HEALTH_CARE_COVERAGE,SMOKER,DRINKER,SOCIAL_DRINKER,HEAVY_ALCOHOL_CONSUMPTION,...,STROKE,DIABETES,ARTHRITIS,MARITAL_STATUS,EMPLOYMENT,SEX,AGE_CATEGORIES,BMICAT,EDUCATION_LEVEL,INCOME
0,2015,2.0,3.0,3.0,2.0,1.0,3.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,4.0,2.0,2.0
1,2015,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,...,2.0,3.0,2.0,2.0,3.0,2.0,7.0,3.0,4.0,1.0
2,2015,2.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,3.0,1.0,2.0,7.0,2.0,11.0,2.0,2.0,NaN
3,2015,2.0,3.0,3.0,2.0,1.0,4.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,3.0,2.0,5.0
4,2015,2.0,3.0,1.0,2.0,1.0,4.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,2.0,3.0,NaN

In [13]:
# Display the first few rows
logging.info("First few rows of the dataset:")
df.head()

2026-01-18 22:25:12 - INFO - First few rows of the dataset:

,YEAR,HEALTH_STATUS,PHYSICAL_HEALTH_STATUS,MENTAL_HEALTH_STATUS,EXERCISE,HEALTH_CARE_COVERAGE,SMOKER,DRINKER,SOCIAL_DRINKER,HEAVY_ALCOHOL_CONSUMPTION,...,STROKE,DIABETES,ARTHRITIS,MARITAL_STATUS,EMPLOYMENT,SEX,AGE_CATEGORIES,BMICAT,EDUCATION_LEVEL,INCOME
0,2015,2.0,3.0,3.0,2.0,1.0,3.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,4.0,2.0,2.0
1,2015,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,...,2.0,3.0,2.0,2.0,3.0,2.0,7.0,3.0,4.0,1.0
2,2015,2.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,3.0,1.0,2.0,7.0,2.0,11.0,2.0,2.0,NaN
3,2015,2.0,3.0,3.0,2.0,1.0,4.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,3.0,2.0,5.0
4,2015,2.0,3.0,1.0,2.0,1.0,4.0,2.0,1.0,1.0,...,2.0,3.0,1.0,1.0,8.0,2.0,9.0,2.0,3.0,NaN

In [14]:
# For each column, print unique values
for col in df.columns:
    print_unique_values(df, col)

10 Unique values in column YEAR of type category: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Categories (10, int64): [2015, 2016, 2017, 2018, ..., 2021, 2022, 2023, 2024]
3 Unique values in column HEALTH_STATUS of type float64: [ 1.  2. nan]
4 Unique values in column PHYSICAL_HEALTH_STATUS of type float64: [ 1.  2.  3. nan]
4 Unique values in column MENTAL_HEALTH_STATUS of type float64: [ 1.  2.  3. nan]
3 Unique values in column EXERCISE of type float64: [ 1.  2. nan]
3 Unique values in column HEALTH_CARE_COVERAGE of type float64: [ 1.  2. nan]
5 Unique values in column SMOKER of type float64: [ 1.  2.  3.  4. nan]
3 Unique values in column DRINKER of type float64: [ 1.  2. nan]
3 Unique values in column SOCIAL_DRINKER of type float64: [ 1.  2. nan]
3 Unique values in column HEAVY_ALCOHOL_CONSUMPTION of type float64: [ 1.  2. nan]
3 Unique values in column HEART_ATTACK of type float64: [ 1.  2. nan]
3 Unique values in column STROKE of type float64: [ 1.  2. nan]
5 Unique values in column DIABETES of type float64: [ 1.  2.  3.  4. nan]
3 Unique values in column ARTHRITIS of type float64: [ 1.  2. nan]
7 Unique values in column MARITAL_STATUS of type float64: [ 1.  2.  3.  4.  5.  6. nan]
9 Unique values in column EMPLOYMENT of type float64: [ 1.  2.  3.  4.  5.  6.  7.  8. nan]
3 Unique values in column SEX of type float64: [ 1.  2. nan]
14 Unique values in column AGE_CATEGORIES of type float64: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. nan]
5 Unique values in column BMICAT of type float64: [ 1.  2.  3.  4. nan]
5 Unique values in column EDUCATION_LEVEL of type float64: [ 1.  2.  3.  4. nan]
8 Unique values in column INCOME of type float64: [ 1.  2.  3.  4.  5.  6.  7. nan]

In [ ]:
# Drop duplicate rows
logging.info("Dropping duplicate rows from the dataset.")
initial_row_count = df.shape[0]
df.drop_duplicates(inplace=True)
logging.info(f"Data after dropping duplicates has {df.shape[0]} rows (dropped {initial_row_count - df.shape[0]} duplicates).")

In [ ]:
# Cleanse and process the data as needed
logging.info("Dropping rows with missing data.")
initial_row_count = df.shape[0]
df.dropna(inplace=True)
logging.info(f"Data after dropping missing rows has {df.shape[0]} rows (dropped {initial_row_count - df.shape[0]} missing data rows).")

In [ ]:
# Bar chart showing data count by year
import matplotlib.pyplot as plt
import numpy as np

# Check if YEAR column has data
if 'YEAR' in df.columns and df['YEAR'].notna().sum() > 0:
    # Count records by year
    year_counts = df['YEAR'].value_counts().sort_index()
    
    # Create figure with better styling
    fig, ax = plt.subplots(figsize=(12, 6))
    
    # Create bar chart
    bars = ax.bar(year_counts.index.astype(str), year_counts.values, color='steelblue', edgecolor='navy', alpha=0.7)
    
    # Customize chart
    ax.set_xlabel('Year', fontsize=12, fontweight='bold')
    ax.set_ylabel('Data Count', fontsize=12, fontweight='bold')
    ax.set_title('BRFSS Data Count by Year (2015-2024)', fontsize=14, fontweight='bold')
    ax.grid(axis='y', alpha=0.3, linestyle='--')
    
    # Add value labels on top of each bar
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{int(height):,}',
                ha='center', va='bottom', fontsize=10, fontweight='bold')
    
    # Rotate x-axis labels for better readability
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()
    
    # Print summary statistics
    print("\n" + "="*50)
    print("Data Count Summary by Year:")
    print("="*50)
    for year, count in year_counts.items():
        print(f"Year {year}: {count:>10,} records")
    print("="*50)
    print(f"Total Records: {year_counts.sum():>10,}")
    print("="*50)
else:
    print("⚠️  YEAR column is empty or missing!")
    print(f"Total rows in dataframe: {len(df):,}")
    print(f"YEAR column null count: {df['YEAR'].isna().sum():,}")
    print("\nTo fix this, you need to:")
    print("1. Ensure the BRFSS_2015_2024.zip file contains a CSV with a YEAR column")
    print("2. Or manually add year information to your dataframe before running this chart")
    print("\nExample of how to add year info if it's missing:")
    print("   df['YEAR'] = df.index // (len(df) // 10)  # Example: distribute into 10 years")

In [ ]:
# For each column, print unique values
for col in df.columns:
    print_unique_values(df, col)

In [ ]:
logging.info(f"The BRFSS 2015-2024 dataset has been successfully prepared and is ready for analysis and had {df.shape[0]} rows and {df.shape[1]} columns.")

In [ ]:
logging.info("Data information:\n")
df.info()

In [ ]:
logging.info("Data description:\n")
df.describe()

In [ ]:
logging.info("First few rows of the dataset:")
df.head()

In [ ]:
df.groupby(['DIABETES']).size()

In [ ]:
def recode_column(df, col_name, old_values, new_values):
    """
    Recode values in a DataFrame column.
    
    Parameters:
    df: pandas DataFrame
    col_name: str, name of column to recode
    old_values: list of current values to replace
    new_values: list of corresponding new values
    
    Returns:
    DataFrame with recoded column (modified in place via assignment)
    """
    if len(old_values) != len(new_values):
        raise ValueError("old_values and new_values must have same length")
    
    mapping = dict(zip(old_values, new_values))
    df[col_name] = df[col_name].replace(mapping)
    return df

In [ ]:
df = recode_column(df, 'DIABETES', [1, 2, 3, 4], [1, 0, 0, 1])
df = recode_column(df, 'HEALTH_STATUS', [1, 2], [1, 0])
df = recode_column(df, 'PHYSICAL_HEALTH_STATUS', [1, 2, 3], [0, 1, 2])
df = recode_column(df, 'MENTAL_HEALTH_STATUS', [1, 2, 3], [0, 1, 2])
df = recode_column(df, 'HEALTH_CARE_COVERAGE', [1, 2], [1, 0])
df = recode_column(df, 'SMOKER', [1, 2, 3, 4], [1, 1, 0, 0])
df = recode_column(df, 'DRINKER', [1, 2], [1, 0])
df = recode_column(df, 'SOCIAL_DRINKER', [1, 2], [0, 1])
df = recode_column(df, 'HEAVY_ALCOHOL_CONSUMPTION', [1, 2], [0, 1])
df = recode_column(df, 'HEART_ATTACK', [1, 2], [1, 0])
df = recode_column(df, 'STROKE', [1, 2], [1, 0])
df = recode_column(df, 'ARTHRITIS', [1, 2], [1, 0])
#df = recode_column(df, 'MARITAL_STATUS', [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6])
#df = recode_column(df, 'EMPLOYMENT', [1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
df.groupby(['DIABETES']).size()

In [ ]:
# For the 'DIABETES' column, update the values as per the following: if 2 or 3, set to 0 (No); if 4 then set to 1 (Pre-Diabetes) if 1, set to 1 (Yes)
df['DIABETES'] = df['DIABETES'].replace({2: 0, 3: 0, 1: 2, 4: 1})

# For 'HEALTH_STATUS', map 2 to 0 (Poor), 1 to 1 (Good)
df['HEALTH_STATUS'] = df['HEALTH_STATUS'].replace({2: 0})

# For 'PHYSICAL_HEALTH_STATUS' and 'MENTAL_HEALTH_STATUS', map values 1-0, 2-1, 3-2
df['PHYSICAL_HEALTH_STATUS'] = df['PHYSICAL_HEALTH_STATUS'].replace({1: 0, 2: 1, 3: 2})
df['MENTAL_HEALTH_STATUS'] = df['MENTAL_HEALTH_STATUS'].replace({1: 0, 2: 1, 3: 2})

# For 'EXERCISE', map 2 to 0 (No), 1 to 1 (Yes) and change type to boolean
df['EXERCISE'] = df['EXERCISE'].replace({2: 0}).astype(bool)

# For 'HEALTH_CARE_COVERAGE', map 2 to 0 (No), 1 to 1 (Yes) and change type to boolean
df['HEALTH_CARE_COVERAGE'] = df['HEALTH_CARE_COVERAGE'].replace({2: 0}).astype(bool)

# For SMOKER, flip the values such that 1 becomes 4, 2 becomes 3, 3 becomes 2, and 4 becomes 1
df['SMOKER'] = df['SMOKER'].replace({1: 8, 2: 7, 3: 6, 4: 5}) - 4